# Generated by Django 2.2.16 on 2020-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20201003_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='people', to='network.Posts'),
        ),
    ]
