# Generated by Django 2.2.16 on 2020-12-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
